[build]
publish = "public"
command = "npm run build"
environment = { NODE_VERSION = "14" }

# [[redirects]]
# from = "https://hildersantos.com/*"
# to = "https://hilder.dev/:splat"
# status = 301
# force = true

# [context.production.environment]
# HUGO_VERSION = "0.54.0"
# HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"

# [context.split1]
# command = "hugo --gc --minify --enableGitInfo"

# [context.split1.environment]
# HUGO_VERSION = "0.54.0"
# HUGO_ENV = "production"

# [context.deploy-preview]
# command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# [context.deploy-preview.environment]
# HUGO_VERSION = "0.54.0"

# [context.branch-deploy]
# command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# [context.branch-deploy.environment]
# HUGO_VERSION = "0.54.0"

# [context.next.environment]
# HUGO_ENABLEGITINFO = "true"
